DEBUG = #-g --farg "-O0"
FARGS =
FCOMP =
FCOMPEXEC =
SO = so
VERBOSE = #-v
FORTHON = Forthon3
PYTHON = python3
BUILDBASEDIR = build3
TEMPBUILDDIR = $(BUILDBASEDIR)/temp
INSTALLOPTIONS = #--user
-include Makefile.local3
BUILDBASE = --build-base $(BUILDBASEDIR)
INSTALLARGS = --pkgbase warp $(BUILDBASE)

install: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/envpydep $(TEMPBUILDDIR)/w3dpydep $(TEMPBUILDDIR)/f3dpydep $(TEMPBUILDDIR)/wxypydep $(TEMPBUILDDIR)/fxypydep $(TEMPBUILDDIR)/wrzpydep $(TEMPBUILDDIR)/frzpydep $(TEMPBUILDDIR)/herpydep $(TEMPBUILDDIR)/cirpydep $(TEMPBUILDDIR)/chopydep $(TEMPBUILDDIR)/em3dpydep ranffortran.c
	$(PYTHON) setup.py $(FCOMP) $(FCOMPEXEC) build $(BUILDBASE) install $(INSTALLOPTIONS)

build: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/envpydep $(TEMPBUILDDIR)/w3dpydep $(TEMPBUILDDIR)/f3dpydep $(TEMPBUILDDIR)/wxypydep $(TEMPBUILDDIR)/fxypydep $(TEMPBUILDDIR)/wrzpydep $(TEMPBUILDDIR)/frzpydep $(TEMPBUILDDIR)/herpydep $(TEMPBUILDDIR)/cirpydep $(TEMPBUILDDIR)/chopydep $(TEMPBUILDDIR)/em3dpydep ranffortran.c
	$(PYTHON) setup.py $(FCOMP) $(FCOMPEXEC) build $(BUILDBASE)

$(TEMPBUILDDIR)/toppydep: top.F top_lattice.F top_fsl.F dtop.F util.F top.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) top top_lattice.F top_fsl.F dtop.F util.F $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/envpydep: $(TEMPBUILDDIR)/toppydep env.F env.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) env $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/w3dpydep: $(TEMPBUILDDIR)/toppydep w3d.F dw3d.F w3d_injection.F w3d_interp.F w3d_collisions.F w3d_utilities.F w3d_load.F w3d.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) --macros top.v w3d dw3d.F w3d_injection.F w3d_interp.F w3d_collisions.F w3d_load.F w3d_utilities.F $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/f3dpydep: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/w3dpydep f3d.F f3d_mgrid.F f3d_ImplicitES.F f3d_mgrid_be.F f3d_bfield.F f3d_conductors.F fft.F f3d.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) --macros top.v f3d f3d_mgrid.F f3d_ImplicitES.F f3d_mgrid_be.F f3d_bfield.F f3d_conductors.F fft.F $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/wxypydep: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/w3dpydep wxy.F wxy.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) wxy $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/fxypydep: $(TEMPBUILDDIR)/toppydep fxy.F $(TEMPBUILDDIR)/w3dpydep $(TEMPBUILDDIR)/f3dpydep fxy_mgrid.F fxy.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) fxy fxy_mgrid.F $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/wrzpydep: $(TEMPBUILDDIR)/toppydep wrz.F $(TEMPBUILDDIR)/w3dpydep dwrz.F wrz.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) --macros top.v wrz dwrz.F $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/frzpydep: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/w3dpydep $(TEMPBUILDDIR)/f3dpydep frz.F frz_mgrid.F90 frz_mgrid_be.F frz_ImplicitES.F frz.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) frz frz_mgrid.F90 frz_mgrid_be.F frz_ImplicitES.F $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/herpydep: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/wrzpydep her.F her.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) her $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/cirpydep: $(TEMPBUILDDIR)/toppydep cir.F cir.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) cir $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/chopydep: $(TEMPBUILDDIR)/toppydep $(TEMPBUILDDIR)/f3dpydep cho.F cho.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) cho $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/em2dpydep: $(TEMPBUILDDIR)/toppydep em2d.F90 em2d_apml.F90 em2d_apml_cummer.F90 em2d_maxwell.F90 em2d.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) em2d em2d_apml.F90 em2d_apml_cummer.F90 em2d_maxwell.F90 $(INSTALLOPTIONS)
	touch $@

$(TEMPBUILDDIR)/em3dpydep: $(TEMPBUILDDIR)/toppydep em3d.F90 em3d_maxwell.F90 em3d.v
	$(FORTHON) -a --builddir $(TEMPBUILDDIR) $(INSTALLARGS) $(VERBOSE) $(FCOMP) $(FCOMPEXEC) $(FARGS) $(DEBUG) em3d em3d_maxwell.F90 $(INSTALLOPTIONS)
	touch $@

ranffortran.c: ranffortran.m
	$(PYTHON) -c "from Forthon.preprocess import main;main()" ranffortran.m ranffortran.c

clean:
	rm -rf $(BUILDBASEDIR) dist warp.egg-info *.o ../scripts/__version__.py

